version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - ml-service
    volumes:
      - ./backend:/app
    environment:
      - MONGO_URL=mongodb://mongo:27017

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  ml-service:
    build:
      context: ./ml-service
    volumes:
      - ./ml-service:/app # Mount code so it auto-reloads
      - ./.env:/app/.env # Mount .env file
    env_file:
      - .env
    ports:
      - "5001:5001"

volumes:
  mongo_data:
